### ISSUE TITLE
using tab as delimiter for space seperated ld file.

### ISSUE THREAD

**Issue by man4ish** [ArnaudDroitLab/LD-annot#1]
I noticed while parsing mydata.ld file tab is being used as seperator while it is space seperated. So i changed this line as following.

       #l = line.strip().split('\t')     # line 405 
        l = line.strip().split(' ')   #use space instead of tab

it is working fine. Can you pls double check the logic here and confirm me the reason for using tab instead of space.

Thanks

**Comment by jprunier-ulaval** [comment]
Using the plink1.9, the separator in mydata.ld is a tab. That's why we set this '\t' as  a separator. I'm curious to know if you really had white space as separator and which plink version you used.
