### ISSUE TITLE
awk fatal error while using LD-annot0.4.py

### ISSUE THREAD

**Issue by nitinra** [ArnaudDroitLab/LD-annot#2]
Hello, 

I am trying to run the LD-annot0.4.py pipeline using the example files (and my own files) and I am getting the following error.
`awk: fatal: cannot open file mydata.ld for reading (No such file or directory)
awk: fatal: cannot open file mydata.ld for reading (No such file or directory)
Traceback (most recent call last):
  File "LD-annot0.4.py", line 374, in <module>
    mean = int(float(l[0]))
IndexError: list index out of range`

Here is my command: 
`LD-annot0.4.py ex_data.vcf ex_annotations.gff ex_candidate_SNPs.txt gene 0.4 example_output`

What could be causing this error? I am using plink/gcc/6.2 and vcftools/0.1.17 on a server.

Thank you!

**Comment by jprunier-ulaval** [comment]
Hi,
First, make sure that the file mydata.ld exists. If not, make sure you're using the right vresion of plink. The one provided in this repository.

Cheers,
